/**
 * 城市字典
 * @authors Yanghuanmin
 * @date    2014-06-13 19:24:42
 * @version 0.1.0
 */

define('data/citydict-zh-cn', function(){
    return {
        "SHA": ["ShangHai", "上海", "SH", "SHA"],
        "HET": ["HuHeHaoTe", "呼和浩特", "HHHT", "HET"],
        "CGD": ["ChangDe", "常德", "CD", "CGD"],
        "PEK": ["BeiJing", "北京", "BJ", "PEK"],
        "CSX": ["ChangSha", "长沙", "CS", "CSX"],
        "CTU": ["ChengDu", "成都", "CD", "CTU"],
        "CKG": ["ChongQing", "重庆", "CQ", "CKG"],
        "HFE": ["HeFei", "合肥", "HF", "HFE"],
        "CGQ": ["ChangChun", "长春", "CC", "CGQ"],
        "HGH": ["HangZhou", "杭州", "HZ", "HGH"],
        "DLC": ["DaLian", "大连", "DL", "DLC"],
        "TNA": ["JiNan", "济南", "JN", "TNA"],
        "FOC": ["FuZhou", "福州", "FZ", "FOC"],
        "JZH": ["JiuZhaiGou", "九寨沟", "JZG", "JZH"],
        "CAN": ["GuangZhou", "广州", "GZ", "CAN"],
        "LJG": ["LiJiang", "丽江", "LJ", "LJG"],
        "KWL": ["GuiLin", "桂林", "GL", "KWL"],
        "LXA": ["LaSa", "拉萨", "LS", "LXA"],
        "KWE": ["Guiyang", "贵阳", "GY", "KWE"],
        "NGB": ["NingBo", "宁波", "NB", "NGB"],
        "KUS": ["Kunshan", "昆山", "KS", "KUS"],
        "YIW": ["Yiwu", "义乌", "YW", "YIW"],
        "ZJA": ["Zhenjiang", "镇江", "ZJ", "ZJA"],
        "TOX": ["Tongxiang", "桐乡", "TX", "TOX"],
        "HYN": ["Taizhou", "台州", "TZ", "HYN"],
        "DYA": ["Danyang", "丹阳", "DY", "DYA"],
        "SHX": ["Shaoxing", "绍兴", "SX", "SHX"],
        "HRB": ["HaErBin", "哈尔滨", "HEB", "HRB"],
        "NTG": ["NanTong", "南通", "NT", "NTG"],
        "HAK": ["HaiKou", "海口", "HK", "HAK"],
        "NKG": ["NanJing", "南京", "NJ", "NKG"],
        "KMG": ["KunMing", "昆明", "KM", "KMG"],
        "NNG": ["NanNing", "南宁", "NN", "NNG"],
        "LHW": ["LanZhou", "兰州", "LZ", "LHW"],
        "SJW": ["ShiJiaZhuang", "石家庄", "SJZ", "SJW"],
        "KHN": ["NanChang", "南昌", "NC", "KHN"],
        "TYN": ["TaiYuan", "太原", "TY", "TYN"],
        "TAO": ["QingDao", "青岛", "QD", "TAO"],
        "WUH": ["WuHan", "武汉", "WH", "WUH"],
        "SHE": ["ShenYang", "沈阳", "SY", "SHE"],
        "WUX": ["WuXi", "无锡", "WX", "WUX"],
        "SYX": ["SanYa", "三亚", "SY", "SYX"],
        "XNN": ["XiNing", "西宁", "XN", "XNN"],
        "TSN": ["TianJin", "天津", "TJ", "TSN"],
        "INC": ["YinChuan", "银川", "YC", "INC"],
        "CGO": ["ZhengZhou", "郑州", "ZZ", "CGO"],
        "WXN": ["WanZhou", "万州", "WZ", "WXN"],
        "WNZ": ["WenZhou", "温州", "WZ", "WNZ"],
        "SZX": ["ShenZhen", "深圳", "SZ", "SZX"],
        "URC": ["WuLuMuQi", "乌鲁木齐", "WLMQ", "URC"],
        "YIH": ["YiChang", "宜昌", "YC", "YIH"],
        "XMN": ["XiaMen", "厦门", "XM", "XMN"],
        "SIA": ["XiAn", "西安", "XA", "SIA"],
        "DYG": ["ZhangJiaJie", "张家界", "ZJJ", "DYG"],
        "XUZ": ["XuZhou", "徐州", "XZ", "XUZ"],
        "ZUH": ["ZhuHai", "珠海", "ZH", "ZUH"],
        "MIG": ["MianYang", "绵阳", "MY", "MIG"],
        "HEK": ["HeiHe", "黑河", "HH", "HEK"],
        "XIC": ["XiChang", "西昌", "XC", "XIC"],
        "PZI": ["PanZhiHua", "攀枝花", "PZH", "PZI"],
        "YNT": ["YanTai", "烟台", "YT", "YNT"],
        "CHG": ["ChaoYang", "朝阳", "CY", "CHG"],
        "WEH": ["WeiHai", "威海", "WH", "WEH"],
        "HLD": ["HaiLaEr", "海拉尔", "HLE", "HLD"],
        "LYG": ["LianYunGang", "连云港", "LYG", "LYG"],
        "LZH": ["LiuZhou", "柳州", "LZ", "LZH"],
        "BHY": ["BeiHai", "北海", "BH", "BHY"],
        "HSN": ["ZhouShan", "舟山", "ZS", "HSN"],
        "JNG": ["JiNing", "济宁", "JN", "JNG"],
        "HYN": ["TaiZhou", "台州", "TZ", "HYN"],
        "HJJ": ["HuaiHua", "怀化", "HH", "HJJ"],
        "JJN": ["Quanzhou", "泉州(晋江)", "JJ|QZ|jinjiang", "JJN"],
        "AEB": ["BaiSe", "百色", "BS", "AEB"],
        "SWA": ["JieYang", "揭阳(汕头)", "JY|汕头|shantou|st", "SWA"],
        "TEN": ["TongRen", "铜仁", "TR", "TEN"],
        "ACX": ["XingYi", "兴义", "XY", "ACX"],
        "LZO": ["Luzhou", "泸州", "LZ", "LZO"],
        "HZH": ["LiPing", "黎平", "LP", "HZH"],
        "LYA": ["LuoYang", "洛阳", "LY", "LYA"],
        "LYI": ["LinYi", "临沂", "LY", "LYI"],
        "DOY": ["DongYing", "东营", "DY", "DOY"],
        "HDG": ["HanDan", "邯郸", "HD", "HDG"],
        "ZHA": ["ZhanJiang", "湛江", "ZJ", "ZHA"],
        "KOW": ["GanZhou", "赣州", "GZ", "KOW"],
        "SHP": ["QinHuangDao", "秦皇岛", "QHD", "SHP"],
        "JGS": ["JingGangShan", "井冈山", "JGS", "JGS"],
        "GGN": ["Quanzhou", "泉州", "QZ", "GGN"],
        "TVS": ["TangShan", "唐山", "TS", "TVS"],
        "TYO": ["Ibaraki", "茨城(东京)", "IBRTYO|cicheng|cc|dongjing|dj", "TYO"],
        "HKG": ["Hong Kong", "香港", "HK|xianggang", "HKG"],
        "DIG": ["DiQing", "迪庆", "DQ", "DIG"],
        "TCZ": ["TengChong", "腾冲", "TC", "TCZ"],
        "TAK": ["Takamatsu", "高松", "gs|gaosong", "TAK"],
        "MFM": ["Macau", "澳门", "MC|aomen", "MFM"],
        "YCU": ["YunCheng", "运城", "YC", "YCU"],
        "WUZ": ["WuZhou", "梧州", "WZ", "WUZ"],
        "TGO": ["Tongliao", "通辽", "TL", "TGO"],
        "DAT": ["DaTong", "大同", "DT", "DAT"],
        "JIQ": ["QianJiang", "黔江", "QJ", "JIQ"],
        "HSG": ["Saga", "佐贺(福冈)", "SAGA|zuohe|zh|fugang", "HSG"],
        "YNJ": ["YanJi", "延吉", "YJ", "YNJ"],
        "BKK": ["Mangu", "曼谷", "MG|Bangkok|mangu", "BKK"],
        "BAS": ["ChangBaiShan", "长白山", "CBS ", "BAS"],
        "ZYI": ["Zunyi", "遵义", "ZY ", "ZYI"],
        "HKT": ["Phuket","普吉","PJ|puji","HKT"],
        "NZH": ["Manzhouli", "满洲里", "MZL", "NZH"],
        "REP": ["Siem Reap", "暹粒", "XL|xianli", "REP"],
        "CJU": ["Jeju", "济州岛", "JZ|jizhoudao", "CJU"],
        "BKI": ["Kota Kinabalu", "沙巴", "SB|shaba", "BKI"],
        "SZV": ["SuZhou", "苏州", "SZ", "SZV"],
        "CZX": ["ChangZhou", "常州", "CZ", "CZX"],
        "JIX": ["JiaXing", "嘉兴", "JX", "JIX"],
        "KHH": ["Kaohsiung", "高雄", "GX|Gaoxiong", "KHH"],
        "TVS": ["Tangshan", "唐山", "TS", "TVS"],
        "ZJA": ["Zhenjiang", "镇江", "ZJ", "ZJA"],
        "TPE": ["Taipei", "台北", "TB|taibei", "TPE"],
        "HIA": ["Huaian", "淮安", "HA", "HIA"],
        "OSA": ["Osaka", "大阪", "DB|daban|Osaka", "OSA"],
        "CNX": ["Chiang Mai", "清迈", "QM|qingmai", "CNX"],
        "ZQZ": ["Zhangjiakou", "张家口", "ZJK", "ZQZ"],
        "NRT": ["Tokyo(Narita)", "东京(成田)", "CT|DJ|Dongjing|Chengtian", "NRT"],
        "HIJ": ["Hiroshima", "广岛", "GD|Guangdao", "HIJ"],
        "HKD": ["Hakodate", "函馆", "HG|hanguan", "HKD"],
        "KOJ": ["Kagoshima", "鹿児岛", "LED|Luerdao", "KOJ"],
        "KMJ": ["KMJ", "熊本", "XB|xiongben", "KMJ"],
        "DAD": ["Da Nang", "岘港", "XG|xiangang", "DAD"],
        "SIN": ["Singapore", "新加坡", "XJP|Singapore|xinjiapo", "SIN"],
        "SEL": ["Seoul", "首尔", "SE|ShouEr|Seoul", "SEL"],
        "SPK": ["Sapporo", "札幌", "ZH|ZhaHuang|Sapporo", "SPK"],
        "CYI": ["JiaYi", "嘉义", "JY|JiaYi", "CYI"], //简繁
        "YGJ": ["Tottori", "鸟取", "NQ|Tottori|niaoqu", "YGJ"],
        "IQN": ["Qingyang", "庆阳", "QY", "IQN"],
        "XFN": ["Xiangyang", "襄阳", "XY", "XFN"],
        "JHG": ["Xishuangbanna", "西双版纳", "XSBN|Xishuangbanna", "JHG"],
        "YNZ": ["Yancheng", "盐城", "Yancheng|YC", "YNZ"],
        "KBV": ["Krabi", "甲米", "Jiami|JM", "KBV"],
        "AKJ": ["Xuchuan", "旭川", "Xuchuan|xc", "AKJ"],
        "NGO": ["Nagoya", "名古屋", "mgw|mingguwu", "NGO"],
        "YZY": ["Zhangye", "张掖", "zy|zhangye", "YZY"],
        "HND": ["Tokyo(Haneda)", "东京(羽田)", "Dongjing|Yutian|yt|dj", "HND"],
        "HUN": ["Hualian", "花莲", "Hualian|hl", "HUN"],
        "URT": ["Surat Thani", "素叻他尼(苏梅岛)", "Surat Thani|suletani", "URT"],
        "YTY": ["Yangzhou", "扬州(泰州)", "Yangzhou|yz|taizhou|tz", "YTY"],
        "ENH": ["Enshi", "恩施", "Enshi|es", "ENH"],
        "SQJ": ["Sanming", "三明", "SM", "SQJ"],
        "TEN": ["Tongren", "铜仁", "TR", "TEN"],
        "WDS": ["Wudangshan", "十堰(武当山)", "WDS|sy|shiyan", "WDS"],
        "BAD": ["Baoding", "保定", "BAD|bd|Baoding", "BAD"],
        "HDG": ["Handan", "邯郸", "HDG|hd|Handan", "HDG"],
        "HSU": ["Hengshui", "衡水", "HSU|hs|Hengshui", "HSU"],
        "XNT": ["Xingtai", "邢台", "XNT|xt|Xingtai", "XNT"],
        "DNH": ["Dunhuang", "敦煌", "DNH|dh|Dunhuang", "DNH"],
        "SGN": ["HoChiMinh", "胡志明市", "HoChiMinh|HZM|huzhiming", "SGN"],
        "KJH": ["Kaili", "凯里", "Kaili|kl", "KJH"],
        "PNH": ["Jinbian", "金边", "JinBian|PNH|jb", "PNH"],
        "NNY": ["Nanyang", "南阳", "NanYang|ny", "NNY"],
        "KUL": ["Kuala Lumpu", "吉隆坡", "Kuala Lumpu|jlp|jilongpo|KUL", "KUL"],
        "JHB": ["Johor Bahru", "新山", "Johor Bahru|xs|JHB|xinshan", "JHB"]

    }
});